### ISSUE TITLE
Specifications?

### ISSUE THREAD

**Issue by DataDrug** [Adamant-im/adamant#1]
Hi,

I've just learned about adamant today. It is awesome.
I'm looking forward running a node, what specs would you recomend ?

**Comment by DataDrug** [comment]
Meanwhile, I've setup a VPS to work as a node, but when running NPN TEST i run into this issue:

`npm test

> adamant@0.0.2 test /home/adamant/adamant
> grunt test --verbose

Initializing
Command-line options: --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Initializing config...OK

Registering "tasks" tasks.
Loading "newMigration.js" tasks...OK
+ newMigration

Registering "grunt-obfuscator" local Npm module tasks.
Reading /home/adamant/adamant/node_modules/grunt-obfuscator/package.json...OK
Parsing /home/adamant/adamant/node_modules/grunt-obfuscator/package.json...OK
Loading "index.js" tasks...OK
+ obfuscator

Registering "grunt-exec" local Npm module tasks.
Reading /home/adamant/adamant/node_modules/grunt-exec/package.json...OK
Parsing /home/adamant/adamant/node_modules/grunt-exec/package.json...OK
Loading "exec.js" tasks...OK
+ exec

Registering "grunt-contrib-compress" local Npm module tasks.
Reading /home/adamant/adamant/node_modules/grunt-contrib-compress/package.json..                                                                                                                                                             .OK
Parsing /home/adamant/adamant/node_modules/grunt-contrib-compress/package.json..                                                                                                                                                             .OK
Loading "compress.js" tasks...OK
+ compress

Registering "grunt-eslint" local Npm module tasks.
Reading /home/adamant/adamant/node_modules/grunt-eslint/package.json...OK
Parsing /home/adamant/adamant/node_modules/grunt-eslint/package.json...OK
Loading "eslint.js" tasks...OK
+ eslint
Loading "Gruntfile.js" tasks...OK
+ default, eslint-fix, eslint-nofix, jenkins, release, test

Running tasks: test

Running "test" task

Running "eslint" task

Running "eslint:target" (eslint) task
Verifying property eslint.target exists in config...OK
Files: api, helpers, modules, logic, schema, tasks, test -> target
Options: outputFile=false, quiet=false, maxWarnings=-1, configFile=".eslintrc.js                                                                                                                                                             on", format="codeframe", fix=false
error: 'dapp' is not defined (no-undef) at modules/chats.js:281:70:
  279 |
  280 |                 if (account.secondSignature) {
> 281 |                     var secondHash = library.ed.createPassPhraseHash(dap                                                                                                                                                             p.secondSecret);
      |                                                                      ^
  282 |                     secondKeypair = library.ed.makeKeypair(secondHash);
  283 |                 }
  284 |


error: 'dapp' is not defined (no-undef) at modules/chats.js:293:35:
  291 |                         keypair: keypair,
  292 |                         secondKeypair: secondKeypair,
> 293 |                         category: dapp.category,
      |                                   ^
  294 |                         name: dapp.name,
  295 |                         description: dapp.description,
  296 |                         tags: dapp.tags,


error: 'dapp' is not defined (no-undef) at modules/chats.js:294:31:
  292 |                         secondKeypair: secondKeypair,
  293 |                         category: dapp.category,
> 294 |                         name: dapp.name,
      |                               ^
  295 |                         description: dapp.description,
  296 |                         tags: dapp.tags,
  297 |                         dapp_type: dapp.type,


error: 'dapp' is not defined (no-undef) at modules/chats.js:295:38:
  293 |                         category: dapp.category,
  294 |                         name: dapp.name,
> 295 |                         description: dapp.description,
      |                                      ^
  296 |                         tags: dapp.tags,
  297 |                         dapp_type: dapp.type,
  298 |                         link: dapp.link,


error: 'dapp' is not defined (no-undef) at modules/chats.js:296:31:
  294 |                         name: dapp.name,
  295 |                         description: dapp.description,
> 296 |                         tags: dapp.tags,
      |                               ^
  297 |                         dapp_type: dapp.type,
  298 |                         link: dapp.link,
  299 |                         icon: dapp.icon


error: 'dapp' is not defined (no-undef) at modules/chats.js:297:36:
  295 |                         description: dapp.description,
  296 |                         tags: dapp.tags,
> 297 |                         dapp_type: dapp.type,
      |                                    ^
  298 |                         link: dapp.link,
  299 |                         icon: dapp.icon
  300 |                     });


error: 'dapp' is not defined (no-undef) at modules/chats.js:298:31:
  296 |                         tags: dapp.tags,
  297 |                         dapp_type: dapp.type,
> 298 |                         link: dapp.link,
      |                               ^
  299 |                         icon: dapp.icon
  300 |                     });
  301 |                 } catch (e) {


error: 'dapp' is not defined (no-undef) at modules/chats.js:299:31:
  297 |                         dapp_type: dapp.type,
  298 |                         link: dapp.link,
> 299 |                         icon: dapp.icon
      |                               ^
  300 |                     });
  301 |                 } catch (e) {
  302 |                     return setImmediate(cb, e.toString());


error: 'keypair' is not defined (no-undef) at modules/chats.js:474:65:
  472 |                             }
  473 |
> 474 |                             if (account.multisignatures.indexOf(keypair.                                                                                                                                                             publicKey.toString('hex')) < 0) {
      |                                                                 ^
  475 |                                 return setImmediate(cb, 'Account does no                                                                                                                                                             t belong to multisignature group');
  476 |                             }
  477 |


error: 'keypair' is not defined (no-undef) at modules/chats.js:478:69:
  476 |                             }
  477 |
> 478 |                             modules.accounts.getAccount({publicKey: keyp                                                                                                                                                             air.publicKey}, function (err, requester) {
      |                                                                     ^
  479 |                                 if (err) {
  480 |                                     return setImmediate(cb, err);
  481 |                                 }


error: 'keypair' is not defined (no-undef) at modules/transactions.js:868:65:
  866 |                             }
  867 |
> 868 |                             if (account.multisignatures.indexOf(keypair.                                                                                                                                                             publicKey.toString('hex')) < 0) {
      |                                                                 ^
  869 |                                 return setImmediate(cb, 'Account does no                                                                                                                                                             t belong to multisignature group');
  870 |                             }
  871 |


error: 'keypair' is not defined (no-undef) at modules/transactions.js:872:69:
  870 |                             }
  871 |
> 872 |                             modules.accounts.getAccount({publicKey: keyp                                                                                                                                                             air.publicKey}, function (err, requester) {
      |                                                                     ^
  873 |                                 if (err) {
  874 |                                     return setImmediate(cb, err);
  875 |                                 }


12 errors found.
Warning: Task "eslint:target" failed. Use --force to continue.

Aborted due to warnings.
npm ERR! Test failed.  See above for more details.`


What details do I need to set in order to make it work ?
I suspect it might be about the node owner adress or something to receive the messenger fees, right ?

Sorry if the question is dumb, but I have no idea really.

Thanks.

**Comment by zyuhel** [comment]
Fixed in 0.4.2
